const express=require("express")
const app=express()
const connectDB=require("./database")
const authRoutes=require("./routes/auth.routes")
const userRoutes=require("./routes/user.routes")
const postRoutes=require("./routes/post.routes")
const likeRoutes=require("./routes/like.routes")
const cors=require("cors")
connectDB()
app.use(cors())
app.use(express.json())
app.use(express.urlencoded({extended:true}))
app.use("/api",authRoutes)
app.use("/api",postRoutes)
app.use("/api",userRoutes)
app.use("/api",likeRoutes)
app.get("/",(req,res)=>{
    res.send("welcome to my insta project")
})
app.listen(3000,()=>{
    console.log("server is running")
})
